### ISSUE TITLE
Mouse cursor lost when using Vulkan or OpenGL graphics API when in full-screen mode

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#51] opened 2021-11-18 23:37 UTC
Device: SunSDR2dx
S/N: EED06202100503

Steps to reproduce:

1) Launch EESDR3
2) Select Vulkan or OpenGL as the Graphics API
3) Press Start
4) Mouse cursor is visible across entire screen
5) Click Fullscreen
6) Witness that mouse cursor is only visible in waveform and waterfall areas of screen.  Cursor disappears when in top section and bottom status bar area.

I am able to reproduce this 100%.  DirectX works fine.

EESDR3 version 0.10.0 alpha, build 03112021
Graphics:  AMD Radeon RX580 using latest drivers
Windows 10 Pro, version 21H1, using 125% display scaling
Monitor: Lenovo G34w-10 34-Inch WQHD Curved Gaming Monitor connected via DisplayPort

**Comment by ExpertSDR3** [comment] 2021-12-23 09:01
this behavior is caused by the work of the Qt framework, with the release of new versions of Qt should be fixed

**Closed by ExpertSDR3** 2021-12-23 09:01 UTC
