### ISSUE TITLE
IF Tune Does Not Work If Zoom is <100%

### ISSUE THREAD

**Issue by w3ub** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#479] opened 2022-10-28 18:25 UTC
If I use an E-Coder Plus, with "Use IF" selected, it only behaves this way if the zoom is set to maximum, otherwise the spectrum/waterfall moves with the E-Coder. The mouse for tuning still behaves the way I prefer it, which is locking the spectrum/waterfall.

**Comment by VK6NX** [comment] 2022-11-01 03:31
Tested on DX and SS2(non Pro) E-Coder Plus, MBP M1, MBP Intel, Win 10, Win 11 on zoom ranges from 70% to 140%:
Operations is "Use IF" selecteW3UBd and not selected are all as expected.

@w3ub. Suggestion: remove settings completely, restart ESDR3 and try again

And when next time you feel the case it is recommended to read Bug Submissin Manual first
https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER

**Comment by ExpertSDR3** [comment] 2022-11-01 06:13
This problem was not detected. Can you attach a short video with a demonstration of the problem and show the version of the program?

**Comment by w3ub** [comment] 2022-11-01 13:20
A video is attached. I have only used v3, so I can't comment on v2. I started on the last v3 alpha and just upgraded the other day to the 1.0.0 beta, 28102022. Any zoom other than 100% has this behavior. This was a clean install of v3, as I had no other EESDR SW on the PC.

I am not sure what you mean by "remove settings completely"?

I will try to email my settings if you wish to use them, as this tool does not support that file type.

Doug

https://user-images.githubusercontent.com/116913047/199242324-baa77759-b8a3-42a6-abc7-d4e28be95208.mp4

**Comment by w3ub** [comment] 2022-11-01 13:21
Attached are my settings, see the uploaded video and comments.
Doug

**Comment by VK6NX** [comment] 2022-11-01 14:20
Saying "remove settings completely", I mean go to Appdata folder under User in you windows and delete ESDR3 setting folder from Local (also check in Roaming). This is hard reset of the ESDR3 setting procedure, it should remove any potential conflicts between previous (alphas) settings and current. Obviously, it means you have to re-enter all settings in ESDR3 again after restart, hence, record what you need before manipulating with folders.

And do not use W11 22H2 - this has been discussed hundreds of times. 21H2 is the only non-bugged version currently if you want it under W11. Downgrade to W11 and use any known tweaker to prevent windows upgrading automatically.

**Comment by w3ub** [comment] 2022-11-01 16:53
I have a laptop with the SW on it as well, it runs 21H2. It only had one install, the 0.13.0 alpha, 15092022.

The IF tune behavior is the same on it. 

I deleted the settings folder, and the IF tune issue is the same. I should note that the way I “zoom in” is by right clicking on the mouse on the frequency middle legend bar.

Enabling zoom up and down on the encoder, I can start with 100% zoom, but after about two clicks of zoom in (I don’t see any % shown) the problems comes back.

In this example, I have set the zoom to see a portion of the 17m band, from about 18.1 on the left side and 18.170 on the right. Try this and let me know if the IF tuning is working for you.

Doug

**Comment by w3ub** [comment] 2022-11-01 16:55
I should add, BW set to 312 KHz, maximum to support 80/15/10 meters.

**Comment by VK6NX** [comment] 2022-11-01 22:02
I do not see any issue with IF tune on your video. This is how it suppose to work: when IF in Ecoder configuration selected ON, the zoom center follows VFO and when IF selected OFF - zoom center does not follow VFO.

Ecoder is not emulating mouse.

Anyway, this is not a bug. It more seems that you want some extra functionality. Hence, close it here and open functionality request in https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS

**Comment by ExpertSDR3** [comment] 2022-11-02 09:30
Thanks for the video, it's clear now. Everything works correctly, it is enough to turn on the Scalable waterfall so that the waterfall does not change

![image](https://user-images.githubusercontent.com/93903520/199454284-1260bcbf-3e3c-422a-91e9-b3d849ab06e9.png)

**Comment by w3ub** [comment] 2022-11-02 19:28
One last note … I think the band spread is moving around because the zoom cursor is following the VFO changes with the E-Coder, even though it is unchecked in the contest section of the same screen you mentioned.

Doug

**Closed** 2023-12-19 05:26 UTC
