### ISSUE TITLE
No PC Mic audio output after update to Monterey 12.2

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#254] opened 2022-02-09 08:12 UTC
Software: ExpertSDR3 0.11.0 alpha BUILD: 30122021
Computer: iMac OSX Monterey 12.2
Radio: SunSDR2DX

Since updating to macOS Monterey 12.2 I appear to have lost all audio out when Tx using the Microphone PC input.  I get a carrier signal but no accompanying audio.  When I use a hand mic on Mic 2 on the front panel, I get audio output as expected.

First video I am using the PC Mic.  Something happens when I press Tx/foot switch, but then nothing, and carrier only.

Second video I am using Microphone 2.  Carrier and audio.

https://user-images.githubusercontent.com/47534300/153153234-3a4897be-7c00-40b5-bbd9-989d02d48939.MOV

https://user-images.githubusercontent.com/47534300/153153317-d8d6bcc5-a38d-4653-a737-cb633ab768e9.MOV

**Comment by ExpertSDR3** [comment] 2022-02-11 07:35
I checked on my macbook 2017 with mac OS Monterey 12.2 . The microphone is working, you need to make sure that ExpertSDR 3 has permission to access the microphone.

<img width="669" alt="Screenshot 2022-02-11 at 10 01 12" src="https://user-images.githubusercontent.com/93903520/153552876-4705bac4-b7f0-4c44-b18c-7aaa02d71f36.png">

<img width="1002" alt="Screenshot 2022-02-11 at 10 04 48" src="https://user-images.githubusercontent.com/93903520/153553061-2876c44d-b033-440c-abea-b813cb4dc65a.png">

<img width="979" alt="Screenshot 2022-02-11 at 10 05 27" src="https://user-images.githubusercontent.com/93903520/153553065-905c24c7-0b2a-4122-b28e-350e678349ab.png">

**Comment by reflectingme** [comment] 2022-02-11 07:40
Yep, checked that as per several messages and screenshots to Roman over the past few days.  Upon launch, ExpertSDR3 does not ever ask for permission to access and use the microphone and does not appear in the System > Preferences > Security & Privacy > Privacy > Microphone list

Also using the analyser, no audio trace is present when using any microphone connected using PC Mic.  Mic1 and Mic2 are both fine.

![Screenshot 2022-02-09 at 09 00 44](https://user-images.githubusercontent.com/47534300/153553592-c5a2a586-88c3-48e1-b37f-485218866605.png)
.

**Comment by reflectingme** [comment] 2022-02-11 09:00
> In mac OS Monterey, indeed, the dialog box requesting permission to use the microphone is no longer displayed. Why Apple did this is unclear.

Yep, very strange.  What I don't understand is that how can some machines i.e. yours, running Monterey 12.2 actually use the PC Mic as an input and ExpertSDR3 is listed in the preferences section for microphones, but on other machines i.e. my 2020 iMac it isn't.  I am yet to fully uninstall and reinstall ExpertSDR3, which is something I will be doing at some point today, hopefully prior to 17:00 Moscow time so I can update you guys as to how it went. 

Cheers guys
**John GW3JVB**

**Comment by ExpertSDR3** [comment] 2022-02-11 12:32
Another feature is that if there are several instances of ExpertSDR3 in different directories, only one instance is displayed in the Privacy window. Then you need to run the necessary instance of ExpertSDR3 and uncheck the box in the privacy window and then put it back on and the OS will require you to restart ExpertSDR3. After these actions, the microphone will work for the selected ExpertSDR3 instance,but it will stop working for others.

**Comment by ExpertSDR3** [comment] 2022-02-14 14:30
Judging by the attached screenshot it looks like the displayed list of allowed SW is not complete.
Some applications are above displayed 4 icons and you need to scroll down this list to see other applications.
Hopefully that among those other apps you'll find ESDR3. In case you'll find ESDR3 app in the list, do the described above sequence.

![image](https://user-images.githubusercontent.com/93903520/153882209-468df202-241b-4049-9b83-c91aada805c1.png)

**Comment by reflectingme** [comment] 2022-02-15 08:10
Of course I have looked through the full list, I really am not that daft!!! 😂 ExpertSDR3 is not in the list of any items shown, scrolling up or down reveals several more apps, but none of them are ExpertSDR3.  I elaborated n this in my second post in this thread.

I **am not** able to use the PC Mic in **ExpertSDR3** when using macOS Monterey 12.2.  I **am** able to use the PC Mic in ExpertSDR2 when using Monterey 12.2

The inability to use PC Mic with ExpertSDR3 has been reported by several users, it is a considerable issue that needs to be figured out and resolved as other than using a connected microphone, it pretty much renders ExpertSDR3 unusable.

**Comment by reflectingme** [comment] 2022-02-15 08:11
> Another feature is that if there are several instances of ExpertSDR3 in different directories, only one instance is displayed in the Privacy window. Then you need to run the necessary instance of ExpertSDR3 and uncheck the box in the privacy window and then put it back on and the OS will require you to restart ExpertSDR3. After these actions, the microphone will work for the selected ExpertSDR3 instance,but it will stop working for others.

I have only the single instance of ExpertSDR3 installed.

**Comment by reflectingme** [comment] 2022-03-10 15:22
Also, the BundleID name for ExpertSDR2 is the same as that for ExpertSDR3 - which also might indicate why ExpertSDR3 is not asking for permission to use the Microphone.

However, I did revoke access for ExpertSDR2 to use the Microphone, but ExpertSDR3 still did not ask for permission to access and use the microphone.

**Comment by dd5md** [comment] 2022-03-13 04:28
If you uninstall ExpertSDR2 completely and also delete the two files "eesdr.com.plist" & "com.qtproject.plist" from the directory "~/Library/Preferences/", ExpertSDR3.app will appear in the "Security & Privacy > Privacy > Microphones" directly after opening ExpertSDR3.

I hope when I install ExpertSDR2 afterwards, that it still works :-).

<img width="763" alt="Bildschirmfoto 2022-03-13 um 05 25 35" src="https://user-images.githubusercontent.com/41026754/158045069-5d0a6959-ec1f-480e-a99c-094215bcf5e0.png">

**Comment by reflectingme** [comment] 2022-03-14 08:06
Many thanks for this Mathias, I will try this later today.  However, do you know what qtproject actually is please?  I cannot find reference to it anywhere.  I can see it was installed at the same time as EESDR as the date and time stamps match, but not sure what it is?  I might ask on the test group about it too.  Will update here once I have tried this.

**Comment by dd5md** [comment] 2022-03-15 12:13
Hi John!
The new development environment for the EESDR3 software is QT6 (https://www.qt.io/product/qt6). I'm not sure, but I think that's where it comes from.

Mathias

**Comment by reflectingme** [comment] 2022-03-15 13:55
Ah, thanks Mathias!  I did think it might relate to EE new dev environment thanks for confirming.  Haven't had the opportunity to try your suggestion just yet, hope to try it out later this evening.
John

**Comment by pborges** [comment] 2022-04-09 18:15
@dd5md [dd5md](https://github.com/dd5md) I deleted the Expert Electronics folder from ~/Library/Preferences/ deleted all the apps, then installed ExpertSDR3, went into privacy->mic, unchecked ExpertSDR3 then re-checked it, and finally it works!

I am going to hold off on ExpertSDR2 haha

Thank you for your suggestion hopefully @rvolchkov can fix this in a later release now that the problem has been identified, ExpertSDR3 probably should have a different plist from ExpertSDR2 to stop these sort of issues.

**Comment by reflectingme** [comment] 2022-04-11 10:20
HI Roman @rvolchkov - hope you are well... I was the one to originally bring this to your attention and I am certain this issue is due to the BundleID being the same for both versions of ESDR.  This BundleID should be unique, so as such, when V3 asks behind the scenes for permission to access and use the microphone, the system asks which bundleID is requesting access, sees that it is eesdr.com and that it already has permission, so in this scenario V3 never gets permission to access the Mic.  The plist for each application needs to be unique, and currently V3 does not differentiate from V2.

**Comment by rvolchkov** [comment] 2022-04-11 12:57
Hello, John.
That's perfect, thanks for clarification and simple explanation.
It'll be easy to fix then, look at that @ExpertSDR3

**Comment by reflectingme** [comment] 2022-06-21 06:42
Hi Roman et al, is there any update expected in release 0.13 on this specific issue please?

**Comment by rvolchkov** [comment] 2022-06-21 06:53
Yes, we'll definitely work on this issue in 0.13.0 @ExpertSDR3

**Comment by reflectingme** [comment] 2022-06-21 08:00
Awesome, thanks Roman.

**Comment by reflectingme** [comment] 2022-07-25 17:28
Any update on this issue, Roman?

**Comment by rvolchkov** [comment] 2022-07-26 06:41
I'm not the programmer, thus have nothing to do with actual bug solving.
If the programmer haven't closed this bug report, then I assume there are no updates at this point. Though, it should be soon @ExpertSDR3

**Comment by dd5md** [comment] 2022-08-20 02:35
The bug is still present in ExpertSDR3 0.13.0 alpha. Additionally, the calibration cannot be read after the firmware update.

**Comment by rvolchkov** [comment] 2022-08-22 12:38
With new macOS versions, the situation with Privacy is becoming more and more complicated. 
To get access to Mic, you need to delete ESDR3 from your Mac, you can keep settings folder. Make sure that ESDR3 is not in the list of software with access to Mic.
Then restart your Mac-> install ESDR3 again, launch, select Mic1 and grant access to Mic.
Go to settings and verify that ESDR3 has access to Mic.

If you'll have several instances of ESDR3 on your Mac, only one will have access to Mic. 
Thanks, Apple)

**Comment by dd5md** [comment] 2022-08-28 15:29
Hi,

I have installed "ExpertSDR3" and "ExpertSDR2" on my Macbook Pro (macOS Monterey 12.5.1). For the test I use my second "SunSDR2 DX". The other "SunSDR2 DX" witch I use with "ExpertSDR2" is turned off during the test and the "ExpertSDR2 SunSDR2DX.app" is closed.

"ExpertSDR3" is always recognized as "ExpertSDR2 SunSDR2DX.app" under macOS.

So if "ExpertSDR2 SunSDR2DX.app" is already present under [System Preferences ~> Security & Privacy ~> Privacy ~> Microphone], "ExpertSDR3.app" is not listed because macOS thinks it is the "ExpertSDR2 SunSDR2DX.app".

For example, if I add "ExpertSDR3.app" under [System Preferences ~> Security & Privacy ~> Privacy ~> Full Disk Access], the "ExpertSDR2 SunSDR2DX.app" is added instead of the "ExpertSDR3.app".

I think that the BundleID are still the same for both versions of ESDR. The bug also only occurs with me when both ESDR versions are installed.

Best regards,

Mathias, DD5MD

**Comment by rvolchkov** [comment] 2022-08-29 09:09
@ExpertSDR3 please take a look at the latest comment.

**Comment by reflectingme** [comment] 2022-08-29 10:47
I mentioned the very same thing regarding BundleID of EESDR2 and EESDR3 being the same within iOS causing this issue back in a post in this thread back in April, Roman.  EESDR3 needs a new Bundle ID and all would be resolved.

**Comment by robinmatthews** [comment] 2022-09-14 16:49
Mac: MacBook Pro (16-inch, 2019) - 2.6 GHz 6-Core Intel Core i7
MacOS: 12.6 (21G115)
Radio: SunSDR2DX
ExpertSDR3: 0.13.0 alpha, build 02092022

Scenario:
- New install of MacOS 12.6
- No previous installation of ExpertSDR2 or ExpertSDR3
- Install ExpertSDR3 and RadioSync
- Start ExpertSDR3
- Start radio in software
- Switch from Mic. 1 to Mic. PC
- Change sound card for microphone from 'Unused' to 'Core Audio: MacBook Pro Microphone'
- Enabled sound card
- Switch from Mic. PC to Mic. 1
- Switch from Mic. 1 to Mic. PC

At no point was I asked to give ExpertSDR3 permission to use the microphone. ExpertSDR3 does not appear in the list of applications in System Preferences > Security & Privacy > Privacy > Microphone.

I have subsequently tried rebooting and following the scenario again. I have tried deleting ExpertSDR3, reinstalling ExpertSDR3, and following the scenario again. I have tried deleting the Expert Electronics folder from ~/Library/Preferences/, rebooting and following the scenario.

At no point was I asked to give ExpertSDR3 permission to use the microphone. ExpertSDR3 does not appear in the list of applications in System Preferences > Security & Privacy > Privacy > Microphone.

Thanks
Robin

ps. I have also tried all of the above on a MacBook Pro M1 Max (I know it's not officially supported, but I'm grasping at straws), and all of the above is the same.

**Comment by robin-vss** [comment] 2022-09-15 12:12
Mac: MacBook Pro (16-inch, 2019) - 2.6 GHz 6-Core Intel Core i7
MacOS: 12.6 (21G115)
Radio: SunSDR2DX
ExpertSDR3: 0.13.0 alpha, build 02092022

As an update on my previous report, I installed ExpertSDR2 and when I ran it and switched to the Mic. PC I was asked permission to use the microphone by MacOS. ExpertSDR2 appeared in the System Preferences > Security & Privacy > Privacy > Microphone list and the microphone worked in ExpertSDR2.

I subsequently removed ExpertSDR2 and it's associated preference files. On reboot, System Preferences > Security & Privacy > Privacy > Microphone now showed ExpertSDR3 (because they share the same bundle id) but the microphone does not work in ExpertSDR3.

So for me, operating in a different room to the transceiver, **ExpertSDR3 is non-functional on MacOS**.

**Comment by robinmatthews** [comment] 2022-09-16 08:44
Mac: MacBook Pro (16-inch, 2019) - 2.6 GHz 6-Core Intel Core i7
MacOS: 12.6 (21G115)
Radio: SunSDR2DX
ExpertSDR3: 0.13.0 alpha, build 15092022

Unfortunately it's still unresolved in the new build.

Thanks
Robin

**Comment by VK6NX** [comment] 2022-10-21 03:45
> 

The problem with M1 macs running under 12.x OS is due to apple TCC decoupling Qt Creator permissions from user applications.

This issue was reported in Qt Jira earlier this year, appears to be fixed in QtCreator 8.0 and seems to be re-appeared in QtCreator 8.0.1
Original reports at Qt: https://codereview.qt-project.org/c/qt-creator/qt-creator/+/386978/11

Temporary workaround to get MicPC working: launch ExpertSDR3 application from Terminal:
`% /Applications/ExpertSDR3.app/Contents/MacOS/ExpertSDR3`

On first attempt to use micPC, the Terminal will request permissions to use Microphone; when granted - Terminal will appear in Microphone permission list. 

Important: when application is closed, and re-opened with shortcut from App folder - it will not trigger microphone again. Hence, if you want to continue to use MicPC - use workaround as described the above.

**Comment by ExpertSDR3** [comment] 2022-10-21 07:29
Today there is a solution with access to the microphone, but this is a temporary measure, you need to enter the command into the terminal:

_codesign --force --deep --sign - /Applications/ExpertSDR3.app_

**/Applications/ExpertSDR3.app** - this is the full path to the ESDR3 program, perhaps you have the program in another place, then you will need to specify it.

This was tested on a macbook with instaled xcode and command line tools.

**Comment by VK6NX** [comment] 2022-10-21 11:55
> This was tested on a macbook with instaled xcode and command line tools. We are looking for a solution to this problem.
Was also successfully tested on:
- "clean" M1 (no xcode, no command line tools), MacOS 12.6 and 13.0
- "clean" inlel (2021, no xcode, no command line tools") MacOS 12.6

Additional info! . _codesign_ command has to be re-issued:
- after every new installation of alpha/beta
- in case of Microphone rights has bee revoked by _tccutil reset Microphone eesdr.com_

**Comment by reflectingme** [comment] 2022-10-21 16:30
> Today there is a solution with access to the microphone, but this is a temporary measure, you need to enter the command into the terminal:
> 
> _codesign --force --deep --sign - /Applications/ExpertSDR3.app_
> 
> **/Applications/ExpertSDR3.app** - this is the full path to the ESDR3 program, perhaps you have the program in another place, then you will need to specify it.
> 
> This was tested on a macbook with instaled xcode and command line tools. We are looking for a solution to this problem.

As the user who originally reported this issue, I can confirm this workaround works, and it is the first time since updating my Mac to OSX Monterey that I have been able to use the MicPC as audio input source.

I ran the common in Terminal, and when I launched EESDR3 the first thing was that it asked me for permission to use the Microphone.  Not had a QSO as yet but can see my audio being TX'ed.

Super job guys.
John
GW3JVB

**Comment by dd5md** [comment] 2022-11-04 04:14
In the current ExpertSDR3 1.0.1 beta version the bug is still present. I now believe that basic functions like being able to use a USB mic as a macOS user is not a high priority in development.

**Comment by VK6NX** [comment] 2022-11-04 07:29
> In the current ExpertSDR3 1.0.1 beta version the bug is still present. I now believe that basic functions like being able to use a USB mic as a macOS user is not a high priority in development.

@DD5MD 
You may believe whatever, who cares.

Either use workaround provided above or stop use beta.

Also, if you wish to complain into proper development, go here: https://bugreports.qt.io/ and log the case with them.

**Comment by dd5md** [comment] 2022-11-04 08:11
Hi VK6DX,

A bug tracker is designed to report bugs. You certainly have an idea of the matter. But that is no reason to give such impudent answers.

Best regards dear Gatekeeper!

**Comment by VK6NX** [comment] 2022-11-04 09:22
Precisely, dd5md, precisely.  Report the bugs it is. 

Not promote your believing diversity. Not express your complains. Report the bugs. And this bug already reported, acknowledged, source explained and workaround provided (confirmed solving the issue). 

If you wish to add value - you are more than welcome to go to Apple and Qt and use all your anger and disappointment on those, who are actually the real source of the issue. Perhaps, with your pressure they will fix it faster on Monterey (if the will bother at all).

**Comment by reflectingme** [comment] 2023-02-12 19:09
Unfortunately, this issue seems to have reappeared in 1.0.3 as despite using the correct Terminal command 

codesign --force --deep --sign - /Applications/ExpertSDR3.app

I have in this version sadly lost the use of the external PC Microphone.

**Comment by VK6NX** [comment] 2023-02-12 20:49
Qt says they fix it in 6.5 (which is in beta2 now). Up until ESDR3 moved/tested/confirmed on 6.5, we have to enter the codesign with every new release.

If it does not work at first place in your environment, try to remove previous associations. There was a topic at forum how to do that, I will try to find it.

**Comment by reflectingme** [comment] 2023-02-12 20:54
Awesome, thanks.  I can't recall seeing that forum post so if you are able to pop a link here I'd be most grateful, cheers.

Worked fine since the initial workaround as I posted above on 1.0.1 and 1.0.2 - I guess it must be prev associations which I will look at.  Thanks.

**Comment by VK6NX** [comment] 2023-02-12 21:18
Could not find it either, seems was cleaned up ;)

Try to remove previous association with mic via 
`tccutil reset Microphone`

(just mind this command above removes literally all mics approvals, so if you have some other mics - better look at tccutil help first)

After removing you will need to reboot mac and only after rebooting enter codesign, then re-approve micPC.

If it will not work ... well, then we have to find another way.

**Comment by reflectingme** [comment] 2023-02-12 21:34
When you say other Mics, do you mean ALL other mics such as internal Mic?  Or only any additional external mics I may have added?

**Comment by VK6NX** [comment] 2023-02-12 21:48
All Mic which OS did request to "approve" earlier. They are listed under Privacy & Security: Microphones

**Comment by reflectingme** [comment] 2023-02-12 21:50
Wow, loads of entries in there.  So just to clarify, Mic access will be revoked to each of the items in that list until they are next used when permission will once again be requested?  If that's the case then I'll have a go.

**Comment by VK6NX** [comment] 2023-02-12 21:55
if you enter just`tccutil reset Microphone` - yes, it will revoke all the current list. And then you have to re-approve them at first using application start (when it will be attempting to validate mic).

You can revoke them selectively by entering 
`~ % tccutil reset`
`tccutil: Usage: tccutil reset SERVICE [BUNDLE_ID]`
Where SERVICE = Microphone, and BUNDLE_ID = Mic ID.

Do not remember on top of my head how to ident all mics in Terminal, but the command certainly exists.

**Comment by reflectingme** [comment] 2023-02-12 22:02
Thanks for the info here.  Not sure how to get the Mic ID so may go for the whole lot as I don't see it as an issue when restarting an app when it asks for permission to use the mic.  I'll update here in the morning when I have a bash at this.

**Comment by VK6NX** [comment] 2023-02-12 22:12
https://apple.stackexchange.com/questions/384317/how-do-i-reset-camera-and-microphone-permission-on-macos-mojave

(same as per above on ventura)

And to get bundle id:
`~ % defaults read /Applications/ExpertSDR3.app/Contents/Info.plist CFBundleIdentifier`
`com.eesdr.expertsdr3`

Hence, to perform selective reset of MicPC:
`tccutil reset Microphone com.eesdr.expertsdr3`

Additional info on Apple aggregated devices
--------------------------------------------
If you have used Aggregated Device (as per https://support.apple.com/en-us/HT202000) for MicPC input, then your process might look a bit more complex: you willhave to deal with the permissions on those devices. Whe re-approving the MicPC created under device, it is recommended to remove association first, then remove device from Audio Devices, reboot, create new device in Audio Devices and re-approve it in ESDR3.

Obviously, troubleshooting for aggregated devices is in the above apple link (important predominantly for plug-in USB devices; as of identify of USB devices are not on unique besis in macOS and macOS tracks the repositioning in the USB topology in a plug and play (plug and pray) environment.).



wish it alredy be sorted by Qt in 6.5 :)

**Comment by reflectingme** [comment] 2023-05-07 19:23
Using 1.0.4 I experience the same issue as originally reported here, and that subsequently worked as a temporary fix using the `codesign --force --deep --sign - /Applications/ExpertSDR3.app` statement, but in 1.0.3 and in this version 1.0.4 I again have loss of audio when using external mic.

**Comment by VK6NX** [comment] 2023-05-07 21:41
[make sure you have removed previously granted access](https://eesdr.com/en/forum-en/expertsdr3/10342-enable-micpc-in-macos-ventura-all-mac-models-intel-silicon) and only then codesign the new version

**Comment by reflectingme** [comment] 2023-05-09 09:37
Followed VK6NX advice above and the temporary fix is once again now working fine.

**Closed** 2023-12-19 05:24 UTC
